# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main, dev]        # ajuste conforme o seu fluxo
  pull_request:

###############################################################################
# 1) Build & Test (Node)
###############################################################################
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Instala Node + cache de dependências
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm                # acelera builds subsequentes

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Lint (se existir script)
        run: npm run --if-present lint

      - name: Build (se existir script)
        run: npm run --if-present build

      - name: Tests (se existir script)
        run: npm run --if-present test

###############################################################################
# 2) Setup GCloud (apenas se precisar no CI)
###############################################################################
  setup-gcloud:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
