# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, dev ]      # ajuste conforme seu fluxo
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (opcional) instala dependências e roda testes
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Run lint & tests
        run: |
          npm run lint
          npm test

  # se precisar do gcloud apenas para testes, use o setup padrão — sem componentes extras
  setup-gcloud:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud           # ⬅️  NENHUM install_components aqui
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
