# .github/workflows/ci.yml
name: CI

on:
  push:
    # roda para commits em main OU dev
    branches: [main, dev]
  pull_request:                # roda em todos os PRs que miram main ou dev

jobs:
###############################################################################
# 1) Build & Test (Node)
###############################################################################
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node + cache de dependências
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      # instala dependências
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # scripts opcionais – executa só se existirem
      - name: Lint (se houver)
        run: npm run --if-present lint

      - name: Build (se houver)
        run: npm run --if-present build

      - name: Tests (se houver)
        run: npm run --if-present test

###############################################################################
# 2) Setup GCloud (só se precisar usar GCP no CI)
###############################################################################
  setup-gcloud:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # autentica com a service-account salva em secrets.GCP_SA_KEY
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # gcloud padrão (sem componentes extras)
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
